# Generated by Django 2.1.5 on 2019-02-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-02-19 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
